#AWS_Final_Project/docker-compose.yaml

version: '3.8'

services:
  auth-service:
    build:
      context: ./Backend/Image/auth-service
      dockerfile: Dockerfile
    image: itda-auth:1.6
    # image: itda-auth:test
    container_name: auth-service
    env_file:
      - ./Backend/Image/auth-service/.env
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  search-service:
    build:
      context: ./Backend/Image/search-service
      dockerfile: Dockerfile
    image: itda-search:1.6
    # image: itda-search:test
    container_name: search-service
    env_file:
      - ./Backend/Image/search-service/.env
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lyrics-service:
    build:
      context: ./Backend/Image/lyrics-service
      dockerfile: Dockerfile
    image: itda-lyrics:1.6
    # image: itda-lyrics:test
    container_name: lyrics-service
    env_file:
      - ./Backend/Image/lyrics-service/.env
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  translation-service:
    build:
      context: ./Backend/Image/translation-service
      dockerfile: Dockerfile
    image: itda-translation:1.6
    # image: itda-translation:test
    container_name: translation-service
    env_file:
      - ./Backend/Image/translation-service/.env
    ports:
      - "3004:3004"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  playlist-service:
    build:
      context: ./Backend/Image/playlist-service
      dockerfile: Dockerfile
    image: itda-playlist:1.6
    # image: itda-playlist:test
    container_name: playlist-service
    env_file:
      - ./Backend/Image/playlist-service/.env
    ports:
      - "3005:3005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    build:
      context: ./Frontend/bravo-front
      dockerfile: Dockerfile
      args:
        VITE_FRONTEND_PORT: "5174"
        VITE_AUTH_API_URL: "http://itda-auth.itda-be-ns.svc.cluster.local:3001"
        VITE_SEARCH_API_URL: "http://itda-search.itda-be-ns.svc.cluster.local:3002"
        VITE_LYRICS_API_URL: "http://itda-lyrics.itda-be-ns.svc.cluster.local:3003"
        VITE_TRANSLATION_API_URL: "http://itda-translation.itda-be-ns.svc.cluster.local:3004"
        VITE_PLAYLIST_API_URL: "http://itda-playlist.itda-be-ns.svc.cluster.local:3005"
    image: itda-ui:1.6
    container_name: bravo-front
    # env_file는 빌드 시 사용하지 않고, 혹은 런타임에도 ConfigMap/Secret으로 주입할 수 있으므로 생략 가능
    ports:
      - "5174:5174"
    extra_hosts:
      - "host.docker.internal:host-gateway"




# AWS_Final_Project/docker-compose.yaml
# version: '3.8'

# networks:
#   mynetwork:
#     external: true

# services:
#   auth-service:
#     image: 192.168.2.137:443/backend/itda-auth:test
#     container_name: auth-service
#     env_file:
#       - ./Backend/Image/auth-service/.env
#     ports:
#       - "3001:3001"
#     networks:
#       - mynetwork
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   search-service:
#     image: 192.168.2.137:443/backend/itda-search:test
#     container_name: search-service
#     env_file:
#       - ./Backend/Image/search-service/.env
#     ports:
#       - "3002:3002"
#     networks:
#       - mynetwork
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   lyrics-service:
#     image: 192.168.2.137:443/backend/itda-lyrics:test
#     container_name: lyrics-service
#     env_file:
#       - ./Backend/Image/lyrics-service/.env
#     ports:
#       - "3003:3003"
#     networks:
#       - mynetwork
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   translation-service:
#     image: 192.168.2.137:443/backend/itda-translation:test
#     container_name: translation-service
#     env_file:
#       - ./Backend/Image/translation-service/.env
#     ports:
#       - "3004:3004"
#     networks:
#       - mynetwork
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   playlist-service:
#     image: 192.168.2.137:443/backend/itda-playlist:test
#     container_name: playlist-service
#     env_file:
#       - ./Backend/Image/playlist-service/.env
#     ports:
#       - "3005:3005"
#     networks:
#       - mynetwork
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   app:
#     image: 192.168.2.137:443/frontend/itda-ui:test
#     container_name: bravo-front
#     env_file:
#       - ./Frontend/bravo-front/.env
#     ports:
#       - "5174:5174"
#     networks:
#       - mynetwork
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
