---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-dev
  namespace: itda-fe-ns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dev
  namespace: itda-fe-ns
subjects:
  - kind: User
    name: itda-dev-user
roleRef:
  kind: Role
  name: role-dev
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-sec
  namespace: itda-fe-ns
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-sec
  namespace: itda-fe-ns
subjects:
  - kind: User
    name: itda-sec-user
roleRef:
  kind: Role
  name: role-sec
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-ops
  namespace: itda-fe-ns
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - endpoints
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-ops
  namespace: itda-fe-ns
subjects:
  - kind: User
    name: itda-ops-user
roleRef:
  kind: Role
  name: role-ops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-dev
  namespace: itda-be-ns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dev
  namespace: itda-be-ns
subjects:
  - kind: User
    name: itda-dev-user
roleRef:
  kind: Role
  name: role-dev
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-sec
  namespace: itda-be-ns
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-sec
  namespace: itda-be-ns
subjects:
  - kind: User
    name: itda-sec-user
roleRef:
  kind: Role
  name: role-sec
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-ops
  namespace: itda-be-ns
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - endpoints
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-ops
  namespace: itda-be-ns
subjects:
  - kind: User
    name: itda-ops-user
roleRef:
  kind: Role
  name: role-ops
  apiGroup: rbac.authorization.k8s.io
