apiVersion: v1
kind: ServiceAccount
metadata:
  name: itda-secrets-access
  namespace: itda-fe-ns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::655088038759:role/EKS-SecretsManager-ECR-Role"
    # ↑ Terraform에서 출력된 irsa_role_arn 값 사용
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itda-secrets-access
  namespace: itda-be-ns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::655088038759:role/EKS-SecretsManager-ECR-Role"
    # ↑ Terraform에서 출력된 irsa_role_arn 값 사용
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itda-secrets-access
  namespace: itda-redis-ns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::655088038759:role/EKS-SecretsManager-ECR-Role"
    # ↑ Terraform에서 출력된 irsa_role_arn 값 사용