---
apiVersion: v1
kind: Service
metadata:
  name: itda-ui
  namespace: itda-fe-ns
spec:
  selector:
    app: itda-ui
  type: LoadBalancer
  loadBalancerIP: 192.168.56.130
  ports:
    - name: http
      protocol: TCP
      port: 5174
      targetPort: 5174

---
apiVersion: v1
kind: Service
metadata:
  name: itda-auth
  namespace: itda-be-ns
spec:
  selector:
    app: itda-auth
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: itda-search
  namespace: itda-be-ns
spec:
  selector:
    app: itda-search
    type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: itda-lyrics
  namespace: itda-be-ns
spec:
  selector:
    app: itda-lyrics
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: itda-translation
  namespace: itda-be-ns
spec:
  selector:
    app: itda-translation
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3004
      targetPort: 3004

---
apiVersion: v1
kind: Service
metadata:
  name: itda-playlist
  namespace: itda-be-ns
spec:
  selector:
    app: itda-playlist
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005

---
apiVersion: v1
kind: Service
metadata:
  name: itda-redis-svc
  namespace: itda-redis-ns
spec:
  type: NodePort
  selector:
    app: itda-redis
  ports:
    - port: 6379
      targetPort: 6379
