apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itda-app
  namespace: argocd
  annotations:
    # Image Updater: 여러 이미지를 한 번에 등록 (redis 제외)
    argocd-image-updater.argoproj.io/image-list: |
      ui=655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/itda-ui
      auth=655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/itda-auth
      search=655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/itda-search
      lyrics=655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/itda-lyrics
      translation=655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/itda-translation
      playlist=655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/itda-playlist

    argocd-image-updater.argoproj.io/ui.update-strategy: latest
    argocd-image-updater.argoproj.io/auth.update-strategy: latest
    argocd-image-updater.argoproj.io/search.update-strategy: latest
    argocd-image-updater.argoproj.io/lyrics.update-strategy: latest
    argocd-image-updater.argoproj.io/translation.update-strategy: latest
    argocd-image-updater.argoproj.io/playlist.update-strategy: latest

    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: http://3.39.94.135:8081/bravo/itda.git
    targetRevision: HEAD
    path: k8s-manifests
    # Kustomize 모드
    kustomize:
      # (옵션) namePrefix: itda-
      namePrefix: itda-

  destination:
    server: https://92230E0D25BD970450A7292D7B9DC235.gr7.ap-northeast-2.eks.amazonaws.com
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
