apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-itda-ui
  namespace: itda-fe-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "itda-ui.secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: VITE_BACKEND_URL
            objectAlias: vite_backend_url
  secretObjects:
    - secretName: itda-ui.secret
      type: Opaque
      data:
        - objectName: vite_backend_url
          key: VITE_BACKEND_URL

---
# 02-secretproviderclass-auth.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-itda-auth
  namespace: itda-be-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "itda-auth.secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: GOOGLE_CLIENT_ID
            objectAlias: google_client_id
          - path: GOOGLE_CLIENT_SECRET
            objectAlias: google_client_secret
          - path: GOOGLE_REDIRECT_URI
            objectAlias: google_redirect_uri
          - path: JWT_SECRET
            objectAlias: jwt_secret
          - path: FRONTEND_URL
            objectAlias: frontend_url
          - path: MONGO_URI
            objectAlias: mongo_uri
  secretObjects:
    - secretName: itda-auth.secret
      type: Opaque
      data:
        - objectName: google_client_id
          key: GOOGLE_CLIENT_ID
        - objectName: google_client_secret
          key: GOOGLE_CLIENT_SECRET
        - objectName: google_redirect_uri
          key: GOOGLE_REDIRECT_URI
        - objectName: jwt_secret
          key: JWT_SECRET
        - objectName: frontend_url
          key: FRONTEND_URL
        - objectName: mongo_uri
          key: MONGO_URI
---
# 03-secretproviderclass-search.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-itda-search
  namespace: itda-be-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "itda-search.secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: SPOTIFY_CLIENT_ID
            objectAlias: spotify_client_id
          - path: SPOTIFY_CLIENT_SECRET
            objectAlias: spotify_client_secret
          - path: YOUTUBE_API_KEYS
            objectAlias: youtube_api_keys
          - path: MONGO_URI
            objectAlias: mongo_uri
          - path: REDIS_URL
            objectAlias: redis_url
  secretObjects:
    - secretName: itda-search.secret
      type: Opaque
      data:
        - objectName: spotify_client_id
          key: SPOTIFY_CLIENT_ID
        - objectName: spotify_client_secret
          key: SPOTIFY_CLIENT_SECRET
        - objectName: youtube_api_keys
          key: YOUTUBE_API_KEYS
        - objectName: mongo_uri
          key: MONGO_URI
        - objectName: redis_url
          key: REDIS_URL

---
# 04-secretproviderclass-lyrics.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-itda-lyrics
  namespace: itda-be-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "itda-lyrics.secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: LRCLIB_API_BASE
            objectAlias: lrclib_api_base
          - path: MUSIXMATCH_API_KEY
            objectAlias: musixmatch_api_key
          - path: MUSIXMATCH_API_HOST
            objectAlias: musixmatch_api_host
          - path: MONGO_URI
            objectAlias: mongo_uri
  secretObjects:
    - secretName: itda-lyrics.secret
      type: Opaque
      data:
        - objectName: lrclib_api_base
          key: LRCLIB_API_BASE
        - objectName: musixmatch_api_key
          key: MUSIXMATCH_API_KEY
        - objectName: musixmatch_api_host
          key: MUSIXMATCH_API_HOST
        - objectName: mongo_uri
          key: MONGO_URI

---
# 05-secretproviderclass-translation.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-itda-translation
  namespace: itda-be-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "itda-translation.secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_URI
            objectAlias: mongo_uri
          - path: AWS_ACCESS_KEY_ID
            objectAlias: aws_access_key_id
          - path: AWS_SECRET_ACCESS_KEY
            objectAlias: aws_secret_access_key
          - path: AWS_REGION
            objectAlias: aws_region
          - path: INFERENCE_PROFILE_ARN
            objectAlias: inference_profile_arn
  secretObjects:
    - secretName: itda-translation.secret
      type: Opaque
      data:
        - objectName: mongo_uri
          key: MONGO_URI
        - objectName: aws_access_key_id
          key: AWS_ACCESS_KEY_ID
        - objectName: aws_secret_access_key
          key: AWS_SECRET_ACCESS_KEY
        - objectName: aws_region
          key: AWS_REGION
        - objectName: inference_profile_arn
          key: INFERENCE_PROFILE_ARN

---
# 06-secretproviderclass-playlist.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-itda-playlist
  namespace: itda-be-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "itda-playlist.secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_URI
            objectAlias: mongo_uri
  secretObjects:
    - secretName: itda-playlist.secret
      type: Opaque
      data:
        - objectName: mongo_uri
          key: MONGO_URI