name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main  # main 브랜치가 변경될 때 실행

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name sonjunhyun
          git config --global user.email leonica0429@gmail.com

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@immense-magpie-lovely.ngrok-free.app/bravo/itda.git
          git fetch gitlab
          git branch -u gitlab/main main || git push --set-upstream gitlab main

      - name: Push to GitLab
        run: |
          git push --mirror gitlab
