name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository (Fetch Full History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 🔥 전체 Git 히스토리를 가져옴

      - name: Configure Git
        run: |
          git config --global user.name "sonjunhyun"
          git config --global user.email "leonica0429@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@immense-magpie-lovely.ngrok-free.app/bravo/itda.git
          git fetch gitlab || echo "GitLab repository is empty"

      - name: Push to GitLab
        run: |
          git push --force gitlab main  # 🔥 강제 푸시 대신 --force 사용